name: "[BE] Petstore Regression Tests"

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment that will be tested'
        required: true
        default: 'staging'
        type: choice
        options:
          - dev
          - staging
          - prod

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  Automation-Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Pet Store Tests
        run: |
          mvn clean test -Dsurefire.suiteXmlFiles=src/test/resources/testSuites/petStoreTestSuite.xml -DENV=${{ inputs.env }} || true

      # Load previous history from gh-pages branch
      - name: Checkout gh-pages branch for history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # Generate Allure report with history
      - name: Generate Allure Report with history
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          allure_results: target/allure-results
          allure_history: allure-history
          gh_pages: gh-pages

      - name: Add .nojekyll file
        run: echo > allure-history/.nojekyll

      # Publish report to GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          destination_dir: allure-reports/${{ inputs.env }}/latest

      - name: Print Allure Report URL
        run: |
          echo "Allure Report: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/allure-reports/${{ inputs.env }}/latest/"
