name: "[BE] Petstore Tests - Allure Report to Pages"

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to test'
        required: true
        default: 'staging'
        type: choice
        options:
          - dev
          - staging
          - prod

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Tests
        run: |
          mvn clean test -Dsurefire.suiteXmlFiles=src/test/resources/testSuites/petStoreTestSuite.xml -DENV=${{ inputs.env }}
        continue-on-error: true

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxvf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
        if: always()

      - name: Generate Allure Report
        run: |
          allure generate target/allure-results -o target/allure-report --clean
        if: always()

      - name: Add .nojekyll
        run: echo "" > target/allure-report/.nojekyll
        if: always()

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'target/allure-report'
        if: always()

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        if: always()

      - name: Print Allure Report URL
        run: |
          echo "✅ Allure Report: ${{ steps.deployment.outputs.page_url }}"
